"""Postgres control plane: SQL translation (always) and a live store (when Postgres answers).

Live tests use INTERLACE_TEST_PG_DSN, or the local disposable container
(``docker run --name interlace-pg -e POSTGRES_PASSWORD=pg -p 5455:5432 postgres:16``).
They create a private schema and drop it. They do not drop databases.
"""

from __future__ import annotations

import os
import uuid

import pytest

from interlace.state.pg import translate
from interlace.streaming.log import Event

DSN = os.environ.get("INTERLACE_TEST_PG_DSN", "postgresql://postgres:pg@localhost:5455/postgres")


@pytest.mark.unit
def test_translate_sqlite_dml_into_postgres() -> None:
    ignored = translate("INSERT OR IGNORE INTO work_queue (idempotency_key) VALUES (?)")
    assert ignored == "INSERT INTO work_queue (idempotency_key) VALUES (%s) ON CONFLICT DO NOTHING"
    replaced = translate("INSERT OR REPLACE INTO trigger_state (trigger_id, last_fired_at) VALUES (?, ?)")
    assert replaced.startswith("INSERT INTO trigger_state")
    assert "ON CONFLICT (trigger_id) DO UPDATE SET last_fired_at = EXCLUDED.last_fired_at" in replaced
    assert "?" not in replaced
    assert translate("BEGIN IMMEDIATE") == "BEGIN"
    assert "GENERATED BY DEFAULT AS IDENTITY" in translate("id INTEGER PRIMARY KEY AUTOINCREMENT")


def _postgres_up() -> bool:
    try:
        import psycopg
    except ImportError:
        return False
    try:
        with psycopg.connect(DSN, connect_timeout=2) as conn:
            conn.execute("SELECT 1")
        return True
    except Exception:
        return False


def _drop_schema(name: str) -> None:
    import psycopg

    with psycopg.connect(DSN, autocommit=True, connect_timeout=2) as conn:
        conn.execute(f"DROP SCHEMA IF EXISTS {name} CASCADE")


@pytest.mark.requires_db
async def test_postgres_store_enqueues_claims_and_logs() -> None:
    pytest.importorskip("psycopg")
    if not _postgres_up():
        pytest.skip("Postgres is not reachable")
    from interlace.state.store import SqliteStateStore

    schema = f"ilstate{uuid.uuid4().hex[:8]}"
    store = await SqliteStateStore.open_postgres(DSN, schema=schema)
    try:
        assert await store.enqueue_run("k", ["m"], None) is True
        assert await store.enqueue_run("k", ["m"], None) is False
        claimed = await store.claim_runs(limit=1, owner="test")
        assert len(claimed) == 1
        assert claimed[0].flow_selector == ["m"]
        assert claimed[0].id > 0
        seq = await store.append_event("run.enqueued", entity="k", payload={"models": ["m"]})
        assert seq > 0
        events = await store.read_events(after_seq=0)
        assert events[-1]["type"] == "run.enqueued"
    finally:
        await store.close()
        _drop_schema(schema)


@pytest.mark.requires_db
async def test_postgres_stream_log_appends_and_dedupes() -> None:
    pytest.importorskip("psycopg")
    if not _postgres_up():
        pytest.skip("Postgres is not reachable")
    from interlace.streaming.log import SqliteStreamLog

    schema = f"illog{uuid.uuid4().hex[:8]}"
    log = None
    try:
        log = await SqliteStreamLog.open_postgres(DSN, schema=schema)
        first = await log.append("orders", [Event(payload={"n": 1}, idempotency_key="a")])
        assert first.offsets == [1]
        assert first.deduped == [False]
        again = await log.append("orders", [Event(payload={"n": 1}, idempotency_key="a")])
        assert again.deduped == [True]
        assert again.offsets == [1]
        stored = await log.read("orders", 0, 10)
        assert [event.payload for event in stored] == [{"n": 1}]
    finally:
        if log is not None:
            await log.close()
        _drop_schema(schema)
